Fix errors when config options missing
mkorthof/freenom-script pull request #43
Opened 2021-06-07 21:41 UTC by nathanfranke

2021-06-11 23:05 UTC, mkorthof commented
Thanks, could you comment on why these changes would be needed?

2021-06-11 23:07 UTC, mkorthof requested changes
Thanks, could you comment on why these changes would be needed?

2021-06-11 23:21 UTC, nathanfranke commented
Can't see if you're referring to the primary changes or the carriage returns (^M)

The primary changes avoid an error when the script compares them with `-eq 1`, by making sure they are not empty (and thus not an integer)

The other changes were done automatically and they are removing the carriage returns.
[See this stack overflow about what they are and how to remove them](https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it)

2021-06-18 11:38 UTC, mkorthof commented
> The primary changes avoid an error when the script compares them with `-eq 1`, by making sure they are not empty (and thus not an integer)

Ah, I see now you added more checks. The only change I noticed before was removed quotes.

2021-06-18 11:40 UTC, mkorthof commented
Ah, I see the added checks now. Only noticed the removed quotes earlier.

2021-06-18 11:44 UTC, mkorthof approved these changes

2021-06-18 11:44 UTC, merged

2021-06-18 11:45 UTC, mkorthof commented
Thanks again 👍🏻